// <auto-generated />
using System;
using Api.UnidadEmprendimiento.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.UnidadEmprendimiento.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250319014255_FixIdentityColumnInVersion")]
    partial class FixIdentityColumnInVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_EVALUACION.Evaluacion", b =>
                {
                    b.Property<int>("EVAL_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EVAL_CODIGO"));

                    b.Property<string>("EVAL_COMENTARIO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EVAL_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("EVAL_FECHACALIFICACION")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EVAL_PROMEDIOCALIFICACION")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EVAL_CODIGO");

                    b.ToTable("EVALUACION", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_EVALUACION.EvaluacionDetalle", b =>
                {
                    b.Property<int>("EVDE_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EVDE_CODIGO"));

                    b.Property<int>("EVAL_CODIGO")
                        .HasColumnType("int");

                    b.Property<decimal>("EVDE_CALIFICACION")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EVDE_COMENTARIO")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool?>("EVDE_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("JURA_CODIGO")
                        .HasColumnType("int");

                    b.Property<int>("PROP_CODIGO")
                        .HasColumnType("int");

                    b.HasKey("EVDE_CODIGO");

                    b.HasIndex("EVAL_CODIGO");

                    b.HasIndex("JURA_CODIGO");

                    b.HasIndex("PROP_CODIGO");

                    b.ToTable("EVALUACIONDETALLE", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_EVALUACION.Item", b =>
                {
                    b.Property<int>("ITEM_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ITEM_CODIGO"));

                    b.Property<int>("EVAL_CODIGO")
                        .HasColumnType("int");

                    b.Property<string>("ITEM_COMENTARIO")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool?>("ITEM_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ITEM_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ITEM_PUNTAJEMAXIMO")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ITEM_CODIGO");

                    b.HasIndex("EVAL_CODIGO");

                    b.ToTable("ITEM", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_EVALUACION.PropuestaJurado", b =>
                {
                    b.Property<int>("PROJ_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PROJ_CODIGO"));

                    b.Property<int>("JURA_CODIGO")
                        .HasColumnType("int");

                    b.Property<DateTime>("PROJ_FECHAASIGNACION")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("PROPJ_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PROP_CODIGO")
                        .HasColumnType("int");

                    b.HasKey("PROJ_CODIGO");

                    b.HasIndex("JURA_CODIGO");

                    b.HasIndex("PROP_CODIGO");

                    b.ToTable("PROPUESTAJURADO", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.BancoElementoFormulario", b =>
                {
                    b.Property<int>("BEFO_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BEFO_CODIGO"));

                    b.Property<string>("BEFO_DATOSJSON")
                        .HasColumnType("TEXT");

                    b.Property<string>("BEFO_ENUNCIADO")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("BEFO_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("BEFO_ORDEN")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("TEFO_CODIGO")
                        .HasColumnType("int");

                    b.HasKey("BEFO_CODIGO");

                    b.HasIndex("TEFO_CODIGO");

                    b.ToTable("BANCOELEMENTOFORMULARIO", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.ConvocatoriaPublicada", b =>
                {
                    b.Property<int>("CONP_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CONP_CODIGO"));

                    b.Property<bool?>("CONP_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CONP_FECHAFIN")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CONP_FECHAINICIO")
                        .HasColumnType("datetime2");

                    b.Property<int>("PERS_CODIGO")
                        .HasColumnType("int");

                    b.HasKey("CONP_CODIGO");

                    b.HasIndex("PERS_CODIGO");

                    b.ToTable("CONVOCATORIAPUBLICADA", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.ElementoFormularioBorrador", b =>
                {
                    b.Property<int>("EFOB_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EFOB_CODIGO"));

                    b.Property<string>("EFOB_DATOSJSON")
                        .HasColumnType("TEXT");

                    b.Property<string>("EFOB_ENUNCIADO")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("EFOB_ESTADO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("EFOB_ORDEN")
                        .HasColumnType("int");

                    b.Property<int>("TEFO_CODIGO")
                        .HasColumnType("int");

                    b.HasKey("EFOB_CODIGO");

                    b.HasIndex("TEFO_CODIGO");

                    b.ToTable("ELEMENTOFORMULARIOBORRADOR", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.ElementoFormularioPublicado", b =>
                {
                    b.Property<int>("EFOP_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EFOP_CODIGO"));

                    b.Property<string>("EFOP_DATOSJSON")
                        .HasColumnType("TEXT");

                    b.Property<string>("EFOP_ENUNCIADO")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("EFOP_ESTADO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("EFOP_ORDEN")
                        .HasColumnType("int");

                    b.Property<int>("TEFO_CODIGO")
                        .HasColumnType("int");

                    b.HasKey("EFOP_CODIGO");

                    b.HasIndex("TEFO_CODIGO");

                    b.ToTable("ELEMENTOFORMULARIOPUBLICADO", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.EstadoFormulario", b =>
                {
                    b.Property<int>("ESTF_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ESTF_CODIGO"));

                    b.Property<bool?>("ESTF_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ESTF_NOMBRE")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ESTF_CODIGO");

                    b.ToTable("ESTADOFORMULARIO", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.FormularioPublicado", b =>
                {
                    b.Property<int>("FORP_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FORP_CODIGO"));

                    b.Property<int>("CONP_CODIGO")
                        .HasColumnType("int");

                    b.Property<int>("ESTF_CODIGO")
                        .HasColumnType("int");

                    b.Property<string>("FORP_DESCRIPCION")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("FORP_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FORP_FECHACREACION")
                        .HasColumnType("datetime2");

                    b.Property<string>("FORP_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TIPF_CODIGO")
                        .HasColumnType("int");

                    b.HasKey("FORP_CODIGO");

                    b.HasIndex("CONP_CODIGO");

                    b.HasIndex("ESTF_CODIGO");

                    b.HasIndex("TIPF_CODIGO");

                    b.ToTable("FORMULARIOPUBLICADO", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GEST_FORMULARIO_BORRADOR.BancoFormularioElemento", b =>
                {
                    b.Property<int>("BFOE_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BFOE_CODIGO"));

                    b.Property<int>("BANF_CODIGO")
                        .HasColumnType("int");

                    b.Property<int>("BEFO_CODIGO")
                        .HasColumnType("int");

                    b.Property<bool?>("BFOE_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("BFOE_CODIGO");

                    b.HasIndex("BANF_CODIGO");

                    b.HasIndex("BEFO_CODIGO");

                    b.ToTable("BANCOFORMULARIOELEMENTO", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GEST_FORMULARIO_BORRADOR.ConvocatoriaBorrador", b =>
                {
                    b.Property<int>("CONB_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CONB_CODIGO"));

                    b.Property<bool?>("CONB_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CONB_FECHAFIN")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CONB_FECHAINICIO")
                        .HasColumnType("datetime2");

                    b.Property<int>("PERS_CODIGO")
                        .HasColumnType("int");

                    b.HasKey("CONB_CODIGO");

                    b.HasIndex("PERS_CODIGO");

                    b.ToTable("CONVOCATORIABORRADOR", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GEST_FORMULARIO_BORRADOR.FormularioBorrador", b =>
                {
                    b.Property<int>("FORB_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FORB_CODIGO"));

                    b.Property<int>("CONB_CODIGO")
                        .HasColumnType("int");

                    b.Property<int>("ESTF_CODIGO")
                        .HasColumnType("int");

                    b.Property<string>("FORB_DESCRIPCION")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("FORB_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FORB_FECHACREACION")
                        .HasColumnType("datetime2");

                    b.Property<string>("FORB_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TIPF_CODIGO")
                        .HasColumnType("int");

                    b.HasKey("FORB_CODIGO");

                    b.HasIndex("CONB_CODIGO");

                    b.HasIndex("ESTF_CODIGO");

                    b.HasIndex("TIPF_CODIGO");

                    b.ToTable("FORMULARIOBORRADOR", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GEST_FORMULARIO_BORRADOR.FormularioElementoBorrador", b =>
                {
                    b.Property<int>("FOEB_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FOEB_CODIGO"));

                    b.Property<int>("EFOB_CODIGO")
                        .HasColumnType("int");

                    b.Property<bool?>("FOEB_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("FORB_CODIGO")
                        .HasColumnType("int");

                    b.HasKey("FOEB_CODIGO");

                    b.HasIndex("EFOB_CODIGO");

                    b.ToTable("FORMULARIOELEMENTOBORRADOR", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GEST_FORMULARIO_PUBLICADO.FormularioElementoPublicado", b =>
                {
                    b.Property<int>("FOEP_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FOEP_CODIGO"));

                    b.Property<int>("EFOP_CODIGO")
                        .HasColumnType("int");

                    b.Property<bool?>("FOEP_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("FORP_CODIGO")
                        .HasColumnType("int");

                    b.HasKey("FOEP_CODIGO");

                    b.HasIndex("EFOP_CODIGO");

                    b.HasIndex("FORP_CODIGO");

                    b.ToTable("FORMULARIOELEMENTOPUBLICADO", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GEST_FORMULARIO_PUBLICADO.VersionFormularioPublicado", b =>
                {
                    b.Property<int>("VFOP_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VFOP_CODIGO"));

                    b.Property<int>("FORP_CODIGO")
                        .HasColumnType("int");

                    b.Property<int>("VERS_CODIGO")
                        .HasColumnType("int");

                    b.Property<bool?>("VFOP_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("VFOP_FECHA")
                        .HasColumnType("datetime2");

                    b.HasKey("VFOP_CODIGO");

                    b.HasIndex("FORP_CODIGO");

                    b.HasIndex("VERS_CODIGO");

                    b.ToTable("VERSIONFORMULARIOPUBLICADO", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GES_BANCO_FORMULARIO.BancoFormulario", b =>
                {
                    b.Property<int>("BANF_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BANF_CODIGO"));

                    b.Property<string>("BANF_DESCRIPCION")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("BANF_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("BANF_FECHACREACION")
                        .HasColumnType("datetime2");

                    b.Property<string>("BANF_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ESTF_CODIGO")
                        .HasColumnType("int");

                    b.Property<int>("TIPF_CODIGO")
                        .HasColumnType("int");

                    b.HasKey("BANF_CODIGO");

                    b.HasIndex("ESTF_CODIGO");

                    b.HasIndex("TIPF_CODIGO");

                    b.ToTable("BANCOFORMULARIO", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GES_BANCO_FORMULARIO.BancoOpcResElemento", b =>
                {
                    b.Property<int>("BORE_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BORE_CODIGO"));

                    b.Property<int>("BEFO_CODIGO")
                        .HasColumnType("int");

                    b.Property<bool?>("BORE_ESTADO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("BORE_ORDEN")
                        .HasColumnType("int");

                    b.Property<string>("BORE_VALOR")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("BORE_CODIGO");

                    b.HasIndex("BEFO_CODIGO");

                    b.ToTable("BANCOOPCRESELEMENTO", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.OpcRespuestaBorrador", b =>
                {
                    b.Property<int>("OPRB_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OPRB_CODIGO"));

                    b.Property<int>("EFOB_CODIGO")
                        .HasColumnType("int");

                    b.Property<bool?>("OPRB_ESTADO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("OPRB_ORDEN")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("OPRB_VALOR")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("OPRB_CODIGO");

                    b.HasIndex("EFOB_CODIGO");

                    b.ToTable("OPCIONRESPUESTABORRADOR", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.OpcRespuestaPublicado", b =>
                {
                    b.Property<int>("OPRP_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OPRP_CODIGO"));

                    b.Property<int>("EFOP_CODIGO")
                        .HasColumnType("int");

                    b.Property<bool?>("OPRP_ESTADO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("OPRP_ORDEN")
                        .HasColumnType("int");

                    b.Property<string>("OPRP_VALOR")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("OPRP_CODIGO");

                    b.HasIndex("EFOP_CODIGO");

                    b.ToTable("OPCIONRESPUESTAPUBLICADO", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.TipoElementoFormulario", b =>
                {
                    b.Property<int>("TPEF_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TPEF_CODIGO"));

                    b.Property<bool?>("TPEF_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("TPEF_NOMBRE")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TPEF_CODIGO");

                    b.ToTable("TIPOELEMENTOFORMULARIO", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.TipoFormulario", b =>
                {
                    b.Property<int>("TIPF_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TIPF_CODIGO"));

                    b.Property<bool?>("TIPF_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("TIPF_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TIPF_CODIGO");

                    b.ToTable("TIPOFORMULARIO", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.EstadoPropuesta", b =>
                {
                    b.Property<int>("ESTP_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ESTP_CODIGO"));

                    b.Property<bool?>("ESTP_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ESTP_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ESTP_CODIGO");

                    b.ToTable("ESTADOPROPUESTA", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.Propuesta", b =>
                {
                    b.Property<int>("PROP_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PROP_CODIGO"));

                    b.Property<int>("CONP_CODIGO")
                        .HasColumnType("int");

                    b.Property<int>("ESTP_CODIGO")
                        .HasColumnType("int");

                    b.Property<decimal>("PROP_CALIFICACION")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("PROP_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("SALA_CODIGO")
                        .HasColumnType("int");

                    b.HasKey("PROP_CODIGO");

                    b.HasIndex("CONP_CODIGO");

                    b.HasIndex("ESTP_CODIGO");

                    b.ToTable("PROPUESTA", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.PropuestaComentario", b =>
                {
                    b.Property<int>("PROC_CODIGO")
                        .HasColumnType("int");

                    b.Property<string>("PROC_COMENTARIO")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PROC_FECHACREACION")
                        .HasColumnType("datetime2");

                    b.Property<int>("VFOP_CODIGO")
                        .HasColumnType("int");

                    b.HasKey("PROC_CODIGO");

                    b.ToTable("PROPUESTA_COMENTARIO", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.Respuesta", b =>
                {
                    b.Property<int>("RESP_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RESP_CODIGO"));

                    b.Property<int>("EFOP_CODIGO")
                        .HasColumnType("int");

                    b.Property<int>("PROP_CODIGO")
                        .HasColumnType("int");

                    b.Property<bool?>("RESP_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("RESP_FECHARESPUESTA")
                        .HasColumnType("datetime2");

                    b.Property<string>("RESP_VALOR")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("RESP_CODIGO");

                    b.HasIndex("EFOP_CODIGO");

                    b.HasIndex("PROP_CODIGO");

                    b.ToTable("RESPUESTA", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.UsuarioPropuesta", b =>
                {
                    b.Property<int>("USUP_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("USUP_CODIGO"));

                    b.Property<int>("PERS_CODIGO")
                        .HasColumnType("int");

                    b.Property<int>("PROP_CODIGO")
                        .HasColumnType("int");

                    b.Property<bool?>("USUP_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("USUP_FECHAASOCIACION")
                        .HasColumnType("datetime2");

                    b.HasKey("USUP_CODIGO");

                    b.HasIndex("PERS_CODIGO");

                    b.HasIndex("PROP_CODIGO");

                    b.ToTable("USUARIOPROPUESTA", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.VersionP", b =>
                {
                    b.Property<int>("VERS_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VERS_CODIGO"));

                    b.Property<int>("PERS_CODIGO")
                        .HasColumnType("int");

                    b.Property<int>("PROP_CODIGO")
                        .HasColumnType("int");

                    b.Property<string>("VERS_COMENTARIO")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("VERS_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("VERS_FECHAMOFICIACION")
                        .HasColumnType("datetime2");

                    b.Property<int>("VERS_NUMERO")
                        .HasColumnType("int");

                    b.HasKey("VERS_CODIGO");

                    b.HasIndex("PERS_CODIGO");

                    b.HasIndex("PROP_CODIGO");

                    b.ToTable("VERSION", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_USUARIO.Jurado", b =>
                {
                    b.Property<int>("JURA_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JURA_CODIGO"));

                    b.Property<string>("JURA_CORREO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("JURA_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("JURA_PAPELLIDO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JURA_PNOMBRE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JURA_SAPELLIDO")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JURA_SNOMBRE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JURA_TELEFONO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JURA_CODIGO");

                    b.ToTable("JURADO", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_USUARIO.Usuario", b =>
                {
                    b.Property<int>("USUA_CODIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("USUA_CODIGO"));

                    b.Property<int>("PERS_CODIGO")
                        .HasColumnType("int");

                    b.Property<string>("USUA_CONTRASENIA")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("USUA_ESTADO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("USUA_NOMBREUSUARIO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("USUA_PAPELLIDO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("USUA_PNOMBRE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("USUA_SAPELLIDO")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("USUA_SNOMBRE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("USUA_CODIGO");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_EVALUACION.EvaluacionDetalle", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_EVALUACION.Evaluacion", "EVALUACION")
                        .WithMany("EVALUACIONDETALLES")
                        .HasForeignKey("EVAL_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_USUARIO.Jurado", "JURADO")
                        .WithMany("EVALUACIONDETALLES")
                        .HasForeignKey("JURA_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.Propuesta", "PROPUESTA")
                        .WithMany("EVALUACIONDETALLES")
                        .HasForeignKey("PROP_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EVALUACION");

                    b.Navigation("JURADO");

                    b.Navigation("PROPUESTA");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_EVALUACION.Item", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_EVALUACION.Evaluacion", "EVALUACION")
                        .WithMany("ITEMS")
                        .HasForeignKey("EVAL_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EVALUACION");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_EVALUACION.PropuestaJurado", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_USUARIO.Jurado", "JURADO")
                        .WithMany("PROPUESTASJURADOS")
                        .HasForeignKey("JURA_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.Propuesta", "PROPUESTA")
                        .WithMany("PROPUESTASJURADOS")
                        .HasForeignKey("PROP_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JURADO");

                    b.Navigation("PROPUESTA");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.BancoElementoFormulario", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.TipoElementoFormulario", "TIPOELEMENTOF")
                        .WithMany("BELEMENTOSF")
                        .HasForeignKey("TEFO_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TIPOELEMENTOF");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.ConvocatoriaPublicada", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_USUARIO.Usuario", "USUARIO")
                        .WithMany("CONVOCATORIASPUBLICADAS")
                        .HasForeignKey("PERS_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("USUARIO");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.ElementoFormularioBorrador", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.TipoElementoFormulario", "TIPOELEMENTOF")
                        .WithMany("ELEMENTOSFB")
                        .HasForeignKey("TEFO_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TIPOELEMENTOF");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.ElementoFormularioPublicado", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.TipoElementoFormulario", "TIPOELEMENTOF")
                        .WithMany("ELEMENTOSFP")
                        .HasForeignKey("TEFO_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TIPOELEMENTOF");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.FormularioPublicado", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.ConvocatoriaPublicada", "CONVOCATORIAPUBLICADA")
                        .WithMany("FORMULARIOSPUBLICADOS")
                        .HasForeignKey("CONP_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.EstadoFormulario", "ESTADOFORMULARIO")
                        .WithMany("FORMULARIOSPUBLICADOS")
                        .HasForeignKey("ESTF_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.TipoFormulario", "TIPOFORMULARIO")
                        .WithMany("FORMULARIOSP")
                        .HasForeignKey("TIPF_CODIGO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CONVOCATORIAPUBLICADA");

                    b.Navigation("ESTADOFORMULARIO");

                    b.Navigation("TIPOFORMULARIO");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GEST_FORMULARIO_BORRADOR.BancoFormularioElemento", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GES_BANCO_FORMULARIO.BancoFormulario", "FORMULARIO")
                        .WithMany("BFORMULARIOSE")
                        .HasForeignKey("BANF_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.BancoElementoFormulario", "ELEMENTOFORMULARIO")
                        .WithMany("BFORMULARIOSE")
                        .HasForeignKey("BEFO_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ELEMENTOFORMULARIO");

                    b.Navigation("FORMULARIO");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GEST_FORMULARIO_BORRADOR.ConvocatoriaBorrador", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_USUARIO.Usuario", "USUARIO")
                        .WithMany("CONVOCATORIASBORRADOR")
                        .HasForeignKey("PERS_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("USUARIO");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GEST_FORMULARIO_BORRADOR.FormularioBorrador", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GEST_FORMULARIO_BORRADOR.ConvocatoriaBorrador", "CONVOCATORIABORRADOR")
                        .WithMany("FORMULARIOSBORRADOR")
                        .HasForeignKey("CONB_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.EstadoFormulario", "ESTADOFORMULARIO")
                        .WithMany("FORMULARIOSBORRADOR")
                        .HasForeignKey("ESTF_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.TipoFormulario", "TIPOFORMULARIO")
                        .WithMany("FORMULARIOSB")
                        .HasForeignKey("TIPF_CODIGO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CONVOCATORIABORRADOR");

                    b.Navigation("ESTADOFORMULARIO");

                    b.Navigation("TIPOFORMULARIO");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GEST_FORMULARIO_BORRADOR.FormularioElementoBorrador", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.ElementoFormularioBorrador", "ELEMENTOBORRADOR")
                        .WithMany("FORMULARIOEB")
                        .HasForeignKey("EFOB_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GEST_FORMULARIO_BORRADOR.FormularioBorrador", "FORMULARIOBORRADOR")
                        .WithMany("FORMULARIOSEB")
                        .HasForeignKey("EFOB_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ELEMENTOBORRADOR");

                    b.Navigation("FORMULARIOBORRADOR");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GEST_FORMULARIO_PUBLICADO.FormularioElementoPublicado", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.ElementoFormularioPublicado", "ELEMENTOFP")
                        .WithMany("FORMULARIOSEP")
                        .HasForeignKey("EFOP_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.FormularioPublicado", "FORMULARIOP")
                        .WithMany("FORMULARIOSEP")
                        .HasForeignKey("FORP_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ELEMENTOFP");

                    b.Navigation("FORMULARIOP");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GEST_FORMULARIO_PUBLICADO.VersionFormularioPublicado", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.FormularioPublicado", "FORMULARIOPUBLICADO")
                        .WithMany("VERSIONESFP")
                        .HasForeignKey("FORP_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.VersionP", "VERSION")
                        .WithMany("VERSIONESFP")
                        .HasForeignKey("VERS_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FORMULARIOPUBLICADO");

                    b.Navigation("VERSION");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GES_BANCO_FORMULARIO.BancoFormulario", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.EstadoFormulario", "ESTADOFORMULARIO")
                        .WithMany("BANCOFORMULARIOS")
                        .HasForeignKey("ESTF_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.TipoFormulario", "TIPOFORMULARIO")
                        .WithMany("BANCOFORMULARIOS")
                        .HasForeignKey("TIPF_CODIGO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ESTADOFORMULARIO");

                    b.Navigation("TIPOFORMULARIO");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GES_BANCO_FORMULARIO.BancoOpcResElemento", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.BancoElementoFormulario", "BELEMENTOF")
                        .WithMany("BANCOOPCRESELEMENTOS")
                        .HasForeignKey("BEFO_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BELEMENTOF");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.OpcRespuestaBorrador", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.ElementoFormularioBorrador", "ELEMENTOFB")
                        .WithMany("OPCRESPUESTASBORRADOR")
                        .HasForeignKey("EFOB_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ELEMENTOFB");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.OpcRespuestaPublicado", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.ElementoFormularioPublicado", "ELEMENTOFP")
                        .WithMany("OPCRESPUESTASPUBLICADOS")
                        .HasForeignKey("EFOP_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ELEMENTOFP");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.Propuesta", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.ConvocatoriaPublicada", "CONVOCATORIAP")
                        .WithMany("PROPUESTAS")
                        .HasForeignKey("CONP_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.EstadoPropuesta", "ESTADOPROPUESTA")
                        .WithMany("PROPUESTAS")
                        .HasForeignKey("ESTP_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CONVOCATORIAP");

                    b.Navigation("ESTADOPROPUESTA");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.PropuestaComentario", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GEST_FORMULARIO_PUBLICADO.VersionFormularioPublicado", "VERSIONFP")
                        .WithMany("PROPUESTASCOMENTARIOS")
                        .HasForeignKey("PROC_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VERSIONFP");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.Respuesta", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.ElementoFormularioPublicado", "ELEMENTOFP")
                        .WithMany("RESPUESTAS")
                        .HasForeignKey("EFOP_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.Propuesta", "PROPUESTA")
                        .WithMany("RESPUESTAS")
                        .HasForeignKey("PROP_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ELEMENTOFP");

                    b.Navigation("PROPUESTA");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.UsuarioPropuesta", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_USUARIO.Usuario", "USUARIO")
                        .WithMany("USUARIOSPROPUESTAS")
                        .HasForeignKey("PERS_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.Propuesta", "PROPUESTA")
                        .WithMany("USUARIOSPROPUESTAS")
                        .HasForeignKey("PROP_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PROPUESTA");

                    b.Navigation("USUARIO");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.VersionP", b =>
                {
                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_USUARIO.Usuario", "USUARIO")
                        .WithMany("VERSIONES")
                        .HasForeignKey("PERS_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.Propuesta", "PROPUESTA")
                        .WithMany("VERSIONES")
                        .HasForeignKey("PROP_CODIGO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PROPUESTA");

                    b.Navigation("USUARIO");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_EVALUACION.Evaluacion", b =>
                {
                    b.Navigation("EVALUACIONDETALLES");

                    b.Navigation("ITEMS");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.BancoElementoFormulario", b =>
                {
                    b.Navigation("BANCOOPCRESELEMENTOS");

                    b.Navigation("BFORMULARIOSE");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.ConvocatoriaPublicada", b =>
                {
                    b.Navigation("FORMULARIOSPUBLICADOS");

                    b.Navigation("PROPUESTAS");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.ElementoFormularioBorrador", b =>
                {
                    b.Navigation("FORMULARIOEB");

                    b.Navigation("OPCRESPUESTASBORRADOR");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.ElementoFormularioPublicado", b =>
                {
                    b.Navigation("FORMULARIOSEP");

                    b.Navigation("OPCRESPUESTASPUBLICADOS");

                    b.Navigation("RESPUESTAS");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.EstadoFormulario", b =>
                {
                    b.Navigation("BANCOFORMULARIOS");

                    b.Navigation("FORMULARIOSBORRADOR");

                    b.Navigation("FORMULARIOSPUBLICADOS");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.FormularioPublicado", b =>
                {
                    b.Navigation("FORMULARIOSEP");

                    b.Navigation("VERSIONESFP");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GEST_FORMULARIO_BORRADOR.ConvocatoriaBorrador", b =>
                {
                    b.Navigation("FORMULARIOSBORRADOR");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GEST_FORMULARIO_BORRADOR.FormularioBorrador", b =>
                {
                    b.Navigation("FORMULARIOSEB");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GEST_FORMULARIO_PUBLICADO.VersionFormularioPublicado", b =>
                {
                    b.Navigation("PROPUESTASCOMENTARIOS");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.GES_BANCO_FORMULARIO.BancoFormulario", b =>
                {
                    b.Navigation("BFORMULARIOSE");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.TipoElementoFormulario", b =>
                {
                    b.Navigation("BELEMENTOSF");

                    b.Navigation("ELEMENTOSFB");

                    b.Navigation("ELEMENTOSFP");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_FORMULARIO.TipoFormulario", b =>
                {
                    b.Navigation("BANCOFORMULARIOS");

                    b.Navigation("FORMULARIOSB");

                    b.Navigation("FORMULARIOSP");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.EstadoPropuesta", b =>
                {
                    b.Navigation("PROPUESTAS");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.Propuesta", b =>
                {
                    b.Navigation("EVALUACIONDETALLES");

                    b.Navigation("PROPUESTASJURADOS");

                    b.Navigation("RESPUESTAS");

                    b.Navigation("USUARIOSPROPUESTAS");

                    b.Navigation("VERSIONES");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_PROPUESTA.VersionP", b =>
                {
                    b.Navigation("VERSIONESFP");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_USUARIO.Jurado", b =>
                {
                    b.Navigation("EVALUACIONDETALLES");

                    b.Navigation("PROPUESTASJURADOS");
                });

            modelBuilder.Entity("Api.UnidadEmprendimiento.Domain.Entities.SQL_SERVER.GEST_USUARIO.Usuario", b =>
                {
                    b.Navigation("CONVOCATORIASBORRADOR");

                    b.Navigation("CONVOCATORIASPUBLICADAS");

                    b.Navigation("USUARIOSPROPUESTAS");

                    b.Navigation("VERSIONES");
                });
#pragma warning restore 612, 618
        }
    }
}
